# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gurl < Formula
  desc "Modern HTTP client CLI with JSON support"
  homepage "https://github.com/geekyharsh05/gurl"
  version "1.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/geekyharsh05/gurl/releases/download/v1.0.0/gurl_1.0.0_darwin_all.tar.gz"
    sha256 "430a087130d193186eb0a7d0b58a679337a95986f0888fd7b1776384b8247132"

    def install
      bin.install "gurl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/geekyharsh05/gurl/releases/download/v1.0.0/gurl_1.0.0_linux_amd64.tar.gz"
      sha256 "3dff54907f314dfd3ea92e1898e2b679d11d4b87e34c9b042123dfe88762241a"
      def install
        bin.install "gurl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/geekyharsh05/gurl/releases/download/v1.0.0/gurl_1.0.0_linux_arm64.tar.gz"
      sha256 "f8961696da9ba203d952136e6b040b24be860424eb1152f5fdc306ea335022ff"
      def install
        bin.install "gurl"
      end
    end
  end
end
