# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gurl < Formula
  desc "Modern HTTP client CLI with JSON support"
  homepage "https://github.com/geekyharsh05/gurl"
  version "1.0.1"
  license "MIT"

  on_macos do
    url "https://github.com/geekyharsh05/gurl/releases/download/v1.0.1/gurl_1.0.1_darwin_all.tar.gz"
    sha256 "02a8f0d24a45e8128a011dbe7db935fc9b91ca41eedaa67ab68f51925db1bc44"

    def install
      bin.install "gurl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/geekyharsh05/gurl/releases/download/v1.0.1/gurl_1.0.1_linux_amd64.tar.gz"
      sha256 "9d6d68f762b9334376161aaa507f7a76c6f602e40d2f7b5d062dd95ecbe306f6"
      def install
        bin.install "gurl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/geekyharsh05/gurl/releases/download/v1.0.1/gurl_1.0.1_linux_arm64.tar.gz"
      sha256 "fe47793b83ff53022feb3927527cadfd97b9610afad27ef69007c78d662567bc"
      def install
        bin.install "gurl"
      end
    end
  end
end
